baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
algolia_docsearch = true
offlineSearch = false
sidebar_search_disable = true

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
