baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params]
algolia_docsearch = false
offlineSearch = true
offlineSearchSummaryLength = 200
offlineSearchMaxResults = 25
sidebar_search_disable = false

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
